name: CustomItemExample
main: petterim1.customitemexample.Main
version: "${pom.version}"
api: ["1.0.22"]
author: PetteriM1
load: STARTUP

commands:
  test:
    permission: test

permissions:
  test:
    default: op
